version: "3.7"
services:
  myapp:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8888:80"
      - "8765:8765"
    tty: true
    stdin_open: true
    volumes:
      - ./html:/var/www/html

  db:
    image: mysql:5.7
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d #初期処理のフォルダ。初回起動のみでおｋ
      - ./mysql/db:/var/lib/mysql #ここにデータ永続化するためのファイルが入る。
    ports:
     - 3306:3306
    environment:
      MYSQL_DATABASE: sampledb
      MYSQL_USER: sample-user
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
  
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"

  pma:
    container_name: pma
    image: phpmyadmin/phpmyadmin:5.0
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 12345678
      
